[package]
name = "e09-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "core"
path = "src/core.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
